Config infra-ci.yml pipeline

diff --git a/ci_gitlab/infra-ci.yml b/ci_gitlab/infra-ci.yml
--- a/ci_gitlab/infra-ci.yml
+++ b/ci_gitlab/infra-ci.yml
@@ -16,4 +16,9 @@ validate_version:
     - 'export VERSION=$(cat app/infra_version.txt)'
     - 'echo "VERSION=${VERSION}"'
     - 'TAG="${CI_COMMIT_REF_NAME}-infra-v${VERSION}"'
-    - 'if ! git fetch --tags || ! git tag | grep -q "^${TAG}$"; then echo "Error: No matching tag ${TAG} found." && exit 1; fi'
+    - 'git fetch --tags'
+    - >
+      'if ! git fetch --tags || ! git tag | grep -q "^${TAG}$"; then 
+        echo "Error: No matching tag ${TAG} found." && exit 1; 
+      fi'
+    
