Config infra-ci.yml pipeline

diff --git a/ci_gitlab/infra-ci.yml b/ci_gitlab/infra-ci.yml
--- a/ci_gitlab/infra-ci.yml
+++ b/ci_gitlab/infra-ci.yml
@@ -19,8 +19,5 @@ validate_version:
     - 'echo ${TAG}'
     - 'git fetch --tags'
     - 'git tag'
-    - >
-      'if ! git fetch --tags || ! git tag | grep -q "^${TAG}$"; then \
-        echo "Error: No matching tag ${TAG} found." && exit 1; \
-      fi'
+    - 'if ! git fetch --tags || ! git tag | grep -q "^${TAG}$"; then echo "Error: No matching tag ${TAG} found." && exit 1;  fi'
     
